### ISSUE TITLE
 java.lang.IllegalArgumentException: argument type mismatch when trying to read a bam

### ISSUE THREAD

**Issue by stkgo** [nvnieuwk/nft-bam#6]
When trying to read a bam file like this:
```
bamData = bam(bamPathString)
```

I get the error:
```
java.lang.IllegalArgumentException: argument type mismatch
```

I have confirmed that the `bamPathString` is in fact a string:
```
 println(bamPathString.getClass().getName()) // prints java.lang.String
```

The bam file does come with an index file and samtools is able to read it. I am not able to provide the bam file or the index but I can show you the flagstat output:
```
1893284 + 0 in total (QC-passed reads + QC-failed reads)
1893284 + 0 primary
0 + 0 secondary
0 + 0 supplementary
0 + 0 duplicates
0 + 0 primary duplicates
0 + 0 mapped (0.00% : N/A)
0 + 0 primary mapped (0.00% : N/A)
1893284 + 0 paired in sequencing
946642 + 0 read1
946642 + 0 read2
0 + 0 properly paired (0.00% : N/A)
0 + 0 with itself and mate mapped
0 + 0 singletons (0.00% : N/A)
0 + 0 with mate mapped to a different chr
0 + 0 with mate mapped to a different chr (mapQ>=5)
```

I then used a try-catch block to get a full stacktrace:
```
  Test [faaba566] 'extract_umi_from_reads' java.lang.IllegalArgumentException: argument type mismatch
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:569)
        at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:107)
        at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323)
        at groovy.lang.MetaClassImpl.setProperty(MetaClassImpl.java:2839)
        at groovy.lang.MetaClassImpl.setProperty(MetaClassImpl.java:3854)
        at org.codehaus.groovy.runtime.InvokerHelper.setProperty(InvokerHelper.java:221)
        at groovy.lang.Closure.setPropertyTryThese(Closure.java:377)
        at groovy.lang.Closure.setPropertyDelegateFirst(Closure.java:367)
        at groovy.lang.Closure.setProperty(Closure.java:348)
        at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.setGroovyObjectProperty(ScriptBytecodeAdapter.java:544)
        at extract_umi_from_reads_test$_run_closure1$_closure2$_closure4$_closure6.doCall(extract_umi_from_reads_test.nf:41)
        at extract_umi_from_reads_test$_run_closure1$_closure2$_closure4$_closure6.doCall(extract_umi_from_reads_test.nf)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:569)
        at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:107)
        at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323)
        at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:274)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1035)
        at groovy.lang.Closure.call(Closure.java:412)
        at groovy.lang.Closure.call(Closure.java:406)
        at com.askimed.nf.test.lang.extensions.GlobalMethods.with(GlobalMethods.java:29)
        at com.askimed.nf.test.lang.extensions.GlobalMethods$with.callStatic(Unknown Source)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallStatic(CallSiteArray.java:55)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callStatic(AbstractCallSite.java:217)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callStatic(AbstractCallSite.java:240)
        at extract_umi_from_reads_test$_run_closure1$_closure2$_closure4.doCall(extract_umi_from_reads_test.nf:29)
        at extract_umi_from_reads_test$_run_closure1$_closure2$_closure4.doCall(extract_umi_from_reads_test.nf)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:569)
        at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:107)
        at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323)
        at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:274)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1035)
        at groovy.lang.Closure.call(Closure.java:412)
        at groovy.lang.Closure.call(Closure.java:406)
        at com.askimed.nf.test.lang.TestCode.execute(TestCode.java:16)
        at com.askimed.nf.test.lang.process.ProcessTest.execute(ProcessTest.java:169)
        at com.askimed.nf.test.core.TestExecutionEngine.execute(TestExecutionEngine.java:214)
        at com.askimed.nf.test.commands.RunTestsCommand.execute(RunTestsCommand.java:184)
        at com.askimed.nf.test.commands.AbstractCommand.call(AbstractCommand.java:41)
        at com.askimed.nf.test.commands.AbstractCommand.call(AbstractCommand.java:17)
        at picocli.CommandLine.executeUserObject(CommandLine.java:1953)
        at picocli.CommandLine.access$1300(CommandLine.java:145)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2352)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2346)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2311)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
        at picocli.CommandLine.execute(CommandLine.java:2078)
        at com.askimed.nf.test.App.run(App.java:44)
        at com.askimed.nf.test.App.main(App.java:51)
```

The bulk of the stacktrace looks like Java and Groovy internals, so I'm at a bit of loss for on how to debug this issue. Is there any guidance you can provide?

**Comment by stkgo** [comment]
Sure, this is the code for the test:
```
nextflow_process {

    name "Test process extract_umi_from_reads"
    script "processes/alignment.nf"
    process "extract_umi_from_reads"

    test("extract_umi_from_reads") {
        when {
            process {
                """
                base_path = "s3://test-inputs/extract_umi_from_reads/"
                bam_path = base_path + "test.bam"

                input[0] = tuple "my_test_sample_id", file(bam_path)
                """
            }
        }
        then {
            assert process.success
            assert process.out.umiBam != null

            with (process.out.umiBam) {
                assert size() == 1
                ArrayList output_tup = get(0)

                // Validate alignment stats
                try {
                        println(output_tup[-1].getClass().getName())
                        bamData = bam(output_tup[-1])
                }
                catch(Exception e) {
                        e.printStackTrace(System.out)
                }

                // Validate checksum
                assert path(output_tup[-1]).md5 == "12924433d505f1eda3a29db054a5d42a"
            }
        }
    }
}
```

And the output from the process being tested is: 
```
    output:
    tuple val(sampleID), file("${sampleID}.withUMI.bam"), emit: umiBam
```

**Comment by stkgo** [comment]
If it helps, I retried this test case with a bam that I am able to share (archive attached) and I receive the same stacktrace. Also, this is the code for the process being tested:

```
process extract_umi_from_reads {

    // there was a publishDir here, but it's been removed for privacy reasons

    input:
    tuple val(sampleID), file(bam)

    output:
    tuple val(sampleID), file("${sampleID}.withUMI.bam"), emit: umiBam

    """
    java -jar /tools/fgbio-1.5.0.jar ExtractUmisFromBam \
        --input=${bam} \
        --output=${sampleID}.withUMI.bam \
        --read-structure="8M143T 8M143T" --molecular-index-tags=ZA ZB --single-tag=RX 
    """
}
```

[test.bam.zip](https://github.com/user-attachments/files/16666333/test.bam.zip)

**Comment by nvnieuwk** [comment]
Thank you for the examples! I tested it out and it seems to only fail when used in a `with` block. I'll open an issue in the nf-test repository because this seems like some bug in the plugins implementation :)

**Comment by stkgo** [comment]
Thank you for looking into this. I can confirm it works fine on my end outside of a `with` block.
